# Generated by Django 2.1.2 on 2018-11-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
